# Generated by Django 2.2.4 on 2019-08-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo', 'codigo_barra')},
        ),
    ]
